### ISSUE TITLE
[ToDo] Deploy Static Site

### ISSUE THREAD

**Issue by designDefined** [xction-dev/xflix#15]
## 요약
- 담당자: @yunsik29 
- 마감 기한: 23-08-18
- 할 일 요약: next 정적 배포

## 작업 내용
- [ ] next 세팅 변경하기
- [ ] next build한 파일들 s3 + cloudfront로 배포하기
- [ ] static 브랜치에 ci/cd 연결

### 1. next 세팅
지금 상태에서는 `yarn build`를 하더라도 정적인 파일들이 생기지 않습니다.
[이 튜토리얼](https://nextjs.org/docs/pages/building-your-application/deploying/static-exports)을 참고하여 `next.config.js`의 output 속성을 'export'로 바꿔주셔야 합니다.
export 시 `/out` 디렉토리에 각종 파일들이 생성되면 성공.

### 2. 배포
배포는 AWS s3와 cloudfront를 이용합니다. 일단 admin IAM을 이용하여 진행하되, 여유가 있다면 IAM 권한 설정을 다시 한 번 보고 새 IAM을 만들어 진행하는 것도 좋을 듯.

### 3. CI/CD
기본적으로 GitHub actions를 이용하기에, `.github/workflows/static.yml` 파일을 적절히 생성해주시면 됩니다.
workflow는 `static` 브랜치가 변경되면 자동 배포되게 설정하시면 됩니다. (static 브랜치는 만들어 두었습니다.)

__중요: AWS 배포에 필요한 모든 정보(IAM의 key, secret key, s3 bucket name, cloudfront distribution ID 등등)는 코드에 직접 작성되지 않고, GitHub의 repository secret으로 저장되어야 합니다. secret 설정에 문제 없도록 권한 설정해두었으니, 혹시 이러한 정보들이 yaml 파일에 포함되지 않도록 주의해주시기 바랍니다!__

## 주의 사항
- #9 를 참고하여 새로운 브랜치를 판 후에 진행해주세요!
- GitHub secret을 이용하여, AWS 관련 정보의 유출을 주의해주세요!

**Comment by designDefined** [comment]
s3 작업의 요지
- 업로드 잘 하기: 드래그 & 드롭 
- 누군가 접근했을 때 index.html을 보여주도록 권한 열어놓기
  - properties에서 static website hosting 기능을 켜주었다. index.html과 404.html을 잘 입력해주었다
  - permissions에서 권한을 잘 작성해준다!

**Comment by designDefined** [comment]
ci/cd 작업의 요지

- 빌드함
- s3에 있는 애들을 싹 지우고
- out 폴더에 있는 것들을 s3에 다시 업로드

**Comment by designDefined** [comment]
cf 작업의 요지
- cdn
- https 인증
- 재배포 시에는 invalidate(무효화)
