### ISSUE TITLE
[ToDo] Initiate server

### ISSUE THREAD

**Issue by designDefined** [xction-dev/xflix#19]
## 요약
- 담당자: @designDefined 
- 마감 기한: 23-08-21
- 할 일 요약: DB 연결, ping-pong API, contents API

## 작업 내용
- [x] MongoDB collection 만들기
- [ ] MongoDB 접속 키 secret으로 등록
- [ ] .env 파일 공유
- [x] 핑퐁 API 만들기
- [x] contents 가져오는 API 만들기
- [x] curations 가져오는 API 만들기
- [x] API docs 작성

## 주의 사항
- MongoDB 접속에 필요한 .env 파일은 슬랙 DM으로 공유
- 서버 PR은 바로 머지하되, 서버 작업이 적용된 프론트엔드 PR은 동적 배포 이후에 머지하기
