### ISSUE TITLE
[ToDo]

### ISSUE THREAD

**Issue by designDefined** [xction-dev/xflix#31]
## 요약
- 담당자:
- 마감 기한: YY-MM-DD
- 할 일 요약: 회원가입과 로그인

## 작업 내용
- [ ] Register 페이지 만들기
- [ ] Register API 연결
- [ ] Login API 연결

### Register Page
- `/register`로 접근할 수 있습니다.
- 피그마에 [Register 페이지](https://www.figma.com/file/DsGVFoEZkGKBYpWMMjCcyv/Xflix?type=design&node-id=174-2&mode=design&t=V1GQdsVmpmQyItZc-0) 추가해 두었습니다
- 작동
  - id, 비밀번호, 이름을 입력할 수 있습니다.
  - 비밀번호와 비밀번호 확인창의 값이 다르면 오류가 발생합니다.
  - '가입' 버튼이 있고, 회원가입에 성공하면 `/login`으로 이동합니다.

### Login Page
- 로그인이 작동합니다.
- 로그인은 이전에 회원가입 한 username과 password로 접근 가능합니다
- 로그인에 성공하면 `/dashboard`로 이동합니다.
- 로그인 정보 저장
  - 로그인 성공 시에 전달되는 name 정보는 웹 스토리지에 저장합니다.
  - 새로고침 시에 로그인 정보는 남아있어야 하지만, 브라우저를 종료하고 다시 접속하거나 새 창으로 접근하면 로그인이 해제되어 있어야 합니다
  - cookie, sessionStorage, localStorage등의 API를 서치하고 적절한 기능을 사용하기

### 변경 사항
- 로그인 시 헤더의 디자인이 변경되었습니다. 피그마의 Dashboard 페이지에서 확인할 수 있습니다.
- api 문서가 업데이트 되었습니다
- `docs/error.md` 파일이 추가되었습니다.
  - API 연결 시 발생하는 에러들은 `error.md`에 적힌 내용을 바탕으로 적절히 처리해주시면 됩니다. (alert 등)

**Comment by nuagenic** [comment]
@designDefined 회원가입 시에 입력하는 회원 정보는 어디에 저장해야 하나요? 이건 웹 스토리지는 아니겠죠?

**Comment by designDefined** [comment]
@nuagenic 입력하는 정보는 어떤걸 말하는건가요?? 회원가입 하고 나면 회원정보는 자동으로 서버에 저장될겁니다!

**Comment by nuagenic** [comment]
@designDefined 엇 회원정보를 말하는 거였습니다! 자동 저장되게 이미 백엔드에 구현이 되어 있다는 건가요? 어디서 확인해보면 될까요?

**Comment by nuagenic** [comment]
아하 api.md에 있었군요 한번 공부해보겠습니다!

**Comment by designDefined** [comment]
넵넵! #30 PR 참고하시면 어떤코드들 작업했는지 볼 수 있습니다~
